SET IDENTITY_INSERT [dbo].[Employee] ON
INSERT INTO [dbo].[Employee] ([Id], [EmployeeName], [EmployeeDepartment]) VALUES (1, N'Roma Marcell', N'Division of Telecommunications Extranet Development')
INSERT INTO [dbo].[Employee] ([Id], [EmployeeName], [EmployeeDepartment]) VALUES (2, N'Hugo Wess', N'Extranet Multimedia Connectivity and Security Division')
INSERT INTO [dbo].[Employee] ([Id], [EmployeeName], [EmployeeDepartment]) VALUES (3, N'Kelvin Lahr', N'Branch of Extranet Implementation')
INSERT INTO [dbo].[Employee] ([Id], [EmployeeName], [EmployeeDepartment]) VALUES (4, N'Janelle Newberg', N'Division of Telecommunications Extranet Development')
INSERT INTO [dbo].[Employee] ([Id], [EmployeeName], [EmployeeDepartment]) VALUES (5, N'Mellie Lombard', N'Branch of Intranet Computer Maintenance and E-Commerce PC Programming')
INSERT INTO [dbo].[Employee] ([Id], [EmployeeName], [EmployeeDepartment]) VALUES (6, N'Reita Abshire', N'Wireless Extranet Backup Team')
INSERT INTO [dbo].[Employee] ([Id], [EmployeeName], [EmployeeDepartment]) VALUES (7, N'Dalila Vickrey', N'Database Programming Branch')
INSERT INTO [dbo].[Employee] ([Id], [EmployeeName], [EmployeeDepartment]) VALUES (8, N'Idella Dallman', N'Branch of Extranet Implementation')
INSERT INTO [dbo].[Employee] ([Id], [EmployeeName], [EmployeeDepartment]) VALUES (9, N'Farah Eldridge', N'Hardware Backup Department')
INSERT INTO [dbo].[Employee] ([Id], [EmployeeName], [EmployeeDepartment]) VALUES (10, N'Lana Montes', N'Hardware Backup Department')
INSERT INTO [dbo].[Employee] ([Id], [EmployeeName], [EmployeeDepartment]) VALUES (11, N'Leola Thornburg', N'Extranet Multimedia Connectivity and Security Division')
INSERT INTO [dbo].[Employee] ([Id], [EmployeeName], [EmployeeDepartment]) VALUES (12, N'Marcelo Paris', N'Database Programming Branch')
INSERT INTO [dbo].[Employee] ([Id], [EmployeeName], [EmployeeDepartment]) VALUES (13, N'Ione Tomlin', N'Multimedia Troubleshooting and Maintenance Team')
INSERT INTO [dbo].[Employee] ([Id], [EmployeeName], [EmployeeDepartment]) VALUES (14, N'Hilario Masterson', N'Multimedia Troubleshooting and Maintenance Team')
INSERT INTO [dbo].[Employee] ([Id], [EmployeeName], [EmployeeDepartment]) VALUES (15, N'Janice Skipper', N'Wireless Extranet Backup Team')
INSERT INTO [dbo].[Employee] ([Id], [EmployeeName], [EmployeeDepartment]) VALUES (16, N'Keren Gillespi', N'Office of Statistical Data Connectivity')
INSERT INTO [dbo].[Employee] ([Id], [EmployeeName], [EmployeeDepartment]) VALUES (17, N'Linh Leitzel', N'Division of Telecommunications Extranet Development')
INSERT INTO [dbo].[Employee] ([Id], [EmployeeName], [EmployeeDepartment]) VALUES (18, N'Rosalia Ayoub', N'Division of Application Security')
INSERT INTO [dbo].[Employee] ([Id], [EmployeeName], [EmployeeDepartment]) VALUES (19, N'Shawna Hood', N'Branch of Intranet Computer Maintenance and E-Commerce PC Programming')
INSERT INTO [dbo].[Employee] ([Id], [EmployeeName], [EmployeeDepartment]) VALUES (20, N'Wilfredo Stumpf', N'Network Maintenance and Multimedia Implementation Committee')
INSERT INTO [dbo].[Employee] ([Id], [EmployeeName], [EmployeeDepartment]) VALUES (21, N'Alexandra Brendle', N'Office of Statistical Data Connectivity')
INSERT INTO [dbo].[Employee] ([Id], [EmployeeName], [EmployeeDepartment]) VALUES (22, N'Luciano Riddell', N'Mainframe PC Development and Practical Source Code Acquisition Team')
INSERT INTO [dbo].[Employee] ([Id], [EmployeeName], [EmployeeDepartment]) VALUES (23, N'Boyce Perales', N'Network Maintenance and Multimedia Implementation Committee')
INSERT INTO [dbo].[Employee] ([Id], [EmployeeName], [EmployeeDepartment]) VALUES (24, N'Alissa Perlman', N'Division of Telecommunications Extranet Development')
INSERT INTO [dbo].[Employee] ([Id], [EmployeeName], [EmployeeDepartment]) VALUES (25, N'Latoyia Kremer', N'Network Maintenance and Multimedia Implementation Committee')
INSERT INTO [dbo].[Employee] ([Id], [EmployeeName], [EmployeeDepartment]) VALUES (26, N'Tawna Blackmore', N'Wireless Extranet Backup Team')
INSERT INTO [dbo].[Employee] ([Id], [EmployeeName], [EmployeeDepartment]) VALUES (27, N'Claudine Valderrama', N'Hardware Backup Department')
INSERT INTO [dbo].[Employee] ([Id], [EmployeeName], [EmployeeDepartment]) VALUES (28, N'Katheryn Lepak', N'Network Maintenance and Multimedia Implementation Committee')
INSERT INTO [dbo].[Employee] ([Id], [EmployeeName], [EmployeeDepartment]) VALUES (29, N'Sage Bow', N'Multimedia Troubleshooting and Maintenance Team')
INSERT INTO [dbo].[Employee] ([Id], [EmployeeName], [EmployeeDepartment]) VALUES (30, N'Altha Rudisill', N'Hardware Backup Department')
INSERT INTO [dbo].[Employee] ([Id], [EmployeeName], [EmployeeDepartment]) VALUES (31, N'Olympia Vien', N'Division of Application Security')
INSERT INTO [dbo].[Employee] ([Id], [EmployeeName], [EmployeeDepartment]) VALUES (32, N'Olene Pyron', N'PC Maintenance Department')
INSERT INTO [dbo].[Employee] ([Id], [EmployeeName], [EmployeeDepartment]) VALUES (33, N'Delorse Searle', N'Extranet Multimedia Connectivity and Security Division')
INSERT INTO [dbo].[Employee] ([Id], [EmployeeName], [EmployeeDepartment]) VALUES (34, N'Greta Quigg', N'Bureau of Business-Oriented PC Backup and Wireless Telecommunications Control')
INSERT INTO [dbo].[Employee] ([Id], [EmployeeName], [EmployeeDepartment]) VALUES (35, N'Kenneth Bowie', N'Branch of Intranet Computer Maintenance and E-Commerce PC Programming')
INSERT INTO [dbo].[Employee] ([Id], [EmployeeName], [EmployeeDepartment]) VALUES (36, N'Colton Kranz', N'Hardware Backup Department')
INSERT INTO [dbo].[Employee] ([Id], [EmployeeName], [EmployeeDepartment]) VALUES (37, N'Kasie Barclay', N'Multimedia Troubleshooting and Maintenance Team')
INSERT INTO [dbo].[Employee] ([Id], [EmployeeName], [EmployeeDepartment]) VALUES (38, N'Thresa Levins', N'Extranet Multimedia Connectivity and Security Division')
INSERT INTO [dbo].[Employee] ([Id], [EmployeeName], [EmployeeDepartment]) VALUES (39, N'Diego Hasbrouck', N'Software Technology and Networking Department')
INSERT INTO [dbo].[Employee] ([Id], [EmployeeName], [EmployeeDepartment]) VALUES (40, N'Tomoko Gale', N'Database Programming Branch')
SET IDENTITY_INSERT [dbo].[Employee] OFF
